SELECT DISTINCT '10953' AS HOSPCODE,
REFERID
REFERID_PROVINCE
PID  
SEQ
AN
REFERID_ORIGIN
HOSPCODE_ORIGIN
DATETIME_SERV
DATETIME_ADMIT
DATETIME_REFER
CLINIC_REFER
HOSP_DESTINATION
CHIEFCOMP
PHYSICALEXAM
DIAGFIRST
DIAGLAST
PSTATUS
PTYPE
EMERGENCY
PTYPEDIS
CAUSEOUT
REQUEST
PROVIDER
DATE_FORMAT(NOW(),'%Y%m%d%H%i%s') AS D_UPDATE