SELECT DISTINCT '10953' AS HOSPCODE,
'' AS PID  
''AS SEQ
''AS AN
''AS DATE_ADMIT
''AS DATE_SERV
''AS DATE_START
''AS DATE_FINISH
''AS REHABCODE
''AS AT_DEVICE
''AS AT_NO
''AS REHABPLACE
''AS PROVIDER
DATE_FORMAT(NOW(),'%Y%m%d%H%i%s') AS D_UPDATE